#!/usr/bin/env python3
"""Writes `design/component-order.md`: the 0.5.0 components and everything they need, in the order to build them.

The data is `tools/component_order.yaml`. A step's *level* is 0 when it needs nothing and otherwise one more than the highest level it needs, so
everything at a level can be built once the levels above it are done, in any order. Within a level the steps that unblock the most come first.

    python tools/generate_component_order.py          # write it
    python tools/generate_component_order.py --check  # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "tools" / "component_order.yaml"
OUT = ROOT / "design" / "component-order.md"
KIND_ORDER = {"tesserae": 0, "mixed": 0, "tre": 1, "adopt": 2, "component": 3}
KIND_LABEL = {"tesserae": "Tesserae", "mixed": "Tesserae + tre", "tre": "tre (engine)", "adopt": "adopt from tre", "component": "component"}


def load() -> dict[str, dict[str, Any]]:
    """Every foundation and unit by id, each with its `kind` ('component' for a unit), `needs` and `issues`."""
    data = yaml.safe_load(DATA.read_text(encoding="utf-8"))
    nodes: dict[str, dict[str, Any]] = {}
    for entry in data["foundations"]:
        nodes[entry["id"]] = {"needs": [], "issues": [], **entry}
    for entry in data["units"]:
        if entry["id"] in nodes:
            raise ValueError(f"{entry['id']} is both a foundation and a unit")
        nodes[entry["id"]] = {"kind": "component", "needs": [], **entry}
    return nodes


def problems(nodes: dict[str, dict[str, Any]]) -> list[str]:
    """What is wrong with the graph: unknown needs, a cycle, an issue placed twice or not at all."""
    out: list[str] = []
    for node in nodes.values():
        for need in node["needs"]:
            if need not in nodes:
                out.append(f"{node['id']} needs {need}, which is not defined")
    placed: dict[int, str] = {}
    for node in nodes.values():
        for issue in node["issues"]:
            if issue in placed:
                out.append(f"#{issue} is in {placed[issue]} and {node['id']}")
            placed[issue] = node["id"]
    out += [f"#{n} is in no unit" for n in range(118, 209) if n not in placed]
    out += [f"#{n} is not a component issue" for n in placed if not 118 <= n <= 208]
    if not out:
        try:
            levels(nodes)
        except ValueError as exc:
            out.append(str(exc))
    return out


def levels(nodes: dict[str, dict[str, Any]]) -> dict[str, int]:
    """Each node's level; a cycle is a ValueError naming it."""
    done: dict[str, int] = {}

    def go(name: str, trail: tuple[str, ...]) -> int:
        if name in done:
            return done[name]
        if name in trail:
            raise ValueError("a cycle: " + " -> ".join((*trail[trail.index(name):], name)))
        done[name] = 1 + max((go(n, (*trail, name)) for n in nodes[name]["needs"]), default=-1)
        return done[name]

    for name in nodes:
        go(name, ())
    return done


def dependents(nodes: dict[str, dict[str, Any]]) -> dict[str, set[str]]:
    """For each node, everything that needs it, directly or through others."""
    direct: dict[str, set[str]] = {name: set() for name in nodes}
    for name, node in nodes.items():
        for need in node["needs"]:
            direct[need].add(name)
    closed: dict[str, set[str]] = {}

    def go(name: str) -> set[str]:
        if name not in closed:
            closed[name] = set()
            for child in direct[name]:
                closed[name] |= {child} | go(child)
        return closed[name]

    return {name: go(name) for name in nodes}


def order(nodes: dict[str, dict[str, Any]]) -> list[str]:
    level, below = levels(nodes), dependents(nodes)
    return sorted(nodes, key=lambda n: (level[n], KIND_ORDER[nodes[n]["kind"]], -len(below[n]), n))


def render() -> str:
    nodes = load()
    bad = problems(nodes)
    if bad:
        raise SystemExit("component_order.yaml: " + "; ".join(bad))
    level, below, sequence = levels(nodes), dependents(nodes), order(nodes)
    step = {name: i + 1 for i, name in enumerate(sequence)}

    def ref(name: str) -> str:
        return f"{nodes[name]['title'].split(' (')[0]} ({step[name]})"

    def label(name: str) -> str:
        node = nodes[name]
        tags = [KIND_LABEL[node["kind"]]]
        if node.get("done"):
            tags.append("done")
        if node.get("optional"):
            tags.append("optional")
        if node.get("gated"):
            tags.append("gated on tre")
        return ", ".join(tags)

    out = ["# The order to build the 0.5.0 components in", "",
           "Generated by `tools/generate_component_order.py` from `tools/component_order.yaml`; do not edit by hand. It answers one question: what has to exist "
           "before each component, so that the 91 component issues ([#115](https://github.com/mindderivative/tesserae/issues/115), #118 to #208) "
           "are worked through without going back.", "",
           "A **step** is a component (or a group built together), a piece of the language or renderer in Tesserae, a change the engine **tre** would "
           "have to make, or a tre capability that exists and could be adopted once what it rests on is built. Its **level** is 0 when it needs "
           "nothing, otherwise one more than the highest level of what it needs: so a level can be built in any order, and a step is never started before "
           "something it needs. Within a level the steps that unblock the most come first. `gated on tre` means Tesserae cannot finish what needs the "
           "step until tre ships it.", ""]
    counts = {k: sum(1 for n in nodes.values() if n["kind"] == k) for k in KIND_LABEL}
    out += [f"{len(nodes)} steps in {max(level.values()) + 1} levels: {counts['component']} components, "
            f"{counts['tesserae'] + counts['mixed']} pieces of Tesserae, {counts['tre']} requests to tre, {counts['adopt']} optional adoptions.", ""]

    out += ["## The order", "", "| Step | Level | What | Kind | Needs first | Unblocks |", "| ---: | ---: | --- | --- | --- | ---: |"]
    for name in sequence:
        node = nodes[name]
        issues = ", ".join(f"#{i}" for i in node["issues"])
        what = f"**{node['title']}**" + (f" ({issues})" if issues else "")
        needs = ", ".join(ref(n) for n in sorted(node["needs"], key=lambda n: step[n])) or "nothing"
        out.append(f"| {step[name]} | {level[name]} | {what} | {label(name)} | {needs} | {len(below[name])} |")
    out.append("")

    out += ["## What each step is", ""]
    for name in sequence:
        node = nodes[name]
        out.append(f"{step[name]}. **{node['title']}** — {label(name)}." + (f" {node['note']}" if node.get("note") else ""))
    out.append("")

    out += ["## What waits on tre", "",
            "Each request to tre, what has to be built before it is worth asking, and the components that cannot be finished until it ships "
            "(`wait`) or that have a workaround meanwhile (`work round it now`).", "",
            "| tre change | Ask after | Components that depend on it |", "| --- | --- | --- |"]
    for name in (n for n in sequence if nodes[n]["kind"] == "tre"):
        node = nodes[name]
        waiting = sorted((d for d in below[name] if nodes[d]["kind"] == "component"), key=lambda d: step[d])
        mark = "wait" if node.get("gated") else "work round it now"
        out.append(f"| {node['title'].removeprefix('tre: ')} ({step[name]}, {mark}) | {', '.join(ref(n) for n in node['needs']) or 'nothing'} | "
                   f"{', '.join(ref(d) for d in waiting) or 'none: an improvement only'} |")
    out.append("")

    finish = nodes.get("textfield-finish")
    if finish:
        out += ["## Where the text field's loose ends went", "",
                "The first component, [#184](https://github.com/mindderivative/tesserae/issues/184), is done except for what depends on other work. "
                f"Those loose ends are the step *{finish['title']}* ({step['textfield-finish']}), which comes after:", ""]
        out += [f"- {ref(need)}" for need in sorted(finish["needs"], key=lambda n: step[n])]
        out += ["", finish.get("note", ""), ""]

    out += ["## Already there since the redesign", "",
            "Several things the component issues were written to ask for exist now and are not steps: call-level `children:` and named slots (L1), "
            "handlers on a call that run in the caller's names and per-item handlers (L2), reactive params (L3), variants as properties selected by "
            "stylesheet rules, with a node's inline style beating rules only for the fields it sets (L4), a full expression language with conditionals, "
            "functions and formatting (L5), handlers that assign Signals and call methods with arguments (L6), local `state:` and the "
            "`hovered`/`focused`/`focus_visible`/`pressed` states (L7), state selectors (L13, partly), dynamic `for:` over a Signal "
            "reconciled by key (L11, partly), recursion, `on_key` and `on_submit`, shipped views with shipped rules, and a schema that checks a view "
            "all the way down.", ""]

    out += ["## Cycles in the issues, and where they were cut", "",
            "The issues name each other in places; a build order needs one direction, so these were decided here:", "",
            "- **Tooltip and IconButton**: IconButton wants a tooltip and a rich tooltip wants a button. The tooltip needs only `Button`, so it comes first.",
            "- **Menu and TextField**: a menu's exposed dropdown is a text field, and a text field's autocomplete is a menu. The field's base is done; the "
            "autocomplete is part of *TextField: what is left*, after the menu.",
            "- **Carousel and Pagination**: pagination's dots serve the carousel. Pagination includes the dots and the carousel uses them.",
            "- **TimePickerDial and Time input**: each names the other as its second mode, so they are one unit with the period selector.",
            "- **Dock and DockPanel**, and **Window and Routed views**: the dock and its panels are one unit; the window comes before routed views, whose "
            "screens it already hosts.",
            "- **Dialog and TopAppBar**: only the full-screen dialog needs the app bar, so that form is its own step after both.",
            "- **SplitButton and Menu**: the split button opens a menu; the menu does not need the split button.",
            "- **FAB menu**: a menu of FABs is made of the FAB and the menu; build it with the steps that use both, after the menu.", ""]

    out += ["## Where each issue went", "", "| Issue | Built as | Step |", "| ---: | --- | ---: |"]
    for issue, name in sorted((i, n) for n, node in nodes.items() for i in node["issues"]):
        out.append(f"| #{issue} | {nodes[name]['title']} | {step[name]} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("design/component-order.md is out of date: run python tools/generate_component_order.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
